### YamlMime:ManagedReference
items:
- uid: GrameFramework.Config
  commentId: N:GrameFramework.Config
  id: GrameFramework.Config
  children:
  - GrameFramework.Config.AudioSettings_SO
  - GrameFramework.Config.DebugSettings_SO
  - GrameFramework.Config.GameplaySettings_SO
  - GrameFramework.Config.GraphicsSettings_SO
  - GrameFramework.Config.InputSettings_SO
  langs:
  - csharp
  - vb
  name: GrameFramework.Config
  nameWithType: GrameFramework.Config
  fullName: GrameFramework.Config
  type: Namespace
  assemblies:
  - cs.temp.dll
references:
- uid: GrameFramework.Config.AudioSettings_SO
  commentId: T:GrameFramework.Config.AudioSettings_SO
  name: AudioSettings_SO
  nameWithType: AudioSettings_SO
  fullName: GrameFramework.Config.AudioSettings_SO
- uid: GrameFramework.Config.DebugSettings_SO
  commentId: T:GrameFramework.Config.DebugSettings_SO
  name: DebugSettings_SO
  nameWithType: DebugSettings_SO
  fullName: GrameFramework.Config.DebugSettings_SO
- uid: GrameFramework.Config.GameplaySettings_SO
  commentId: T:GrameFramework.Config.GameplaySettings_SO
  name: GameplaySettings_SO
  nameWithType: GameplaySettings_SO
  fullName: GrameFramework.Config.GameplaySettings_SO
- uid: GrameFramework.Config.GraphicsSettings_SO
  commentId: T:GrameFramework.Config.GraphicsSettings_SO
  name: GraphicsSettings_SO
  nameWithType: GraphicsSettings_SO
  fullName: GrameFramework.Config.GraphicsSettings_SO
- uid: GrameFramework.Config.InputSettings_SO
  commentId: T:GrameFramework.Config.InputSettings_SO
  name: InputSettings_SO
  nameWithType: InputSettings_SO
  fullName: GrameFramework.Config.InputSettings_SO
