### YamlMime:ManagedReference
items:
- uid: UCTools_ConfigVariables
  commentId: N:UCTools_ConfigVariables
  id: UCTools_ConfigVariables
  children:
  - UCTools_ConfigVariables.BoolConfigVariable
  - UCTools_ConfigVariables.ConfigCategory
  - UCTools_ConfigVariables.ConfigFlags
  - UCTools_ConfigVariables.ConfigVariableBase
  - UCTools_ConfigVariables.EnumConfigVariable`1
  - UCTools_ConfigVariables.FloatConfigVariable
  - UCTools_ConfigVariables.IntConfigVariable
  - UCTools_ConfigVariables.QualityConfigVariable
  - UCTools_ConfigVariables.QualityOption
  - UCTools_ConfigVariables.QualityOptionExtensions
  - UCTools_ConfigVariables.ResolutionConfigVariable
  - UCTools_ConfigVariables.ResolutionOption
  - UCTools_ConfigVariables.ResolutionOptionExtensions
  - UCTools_ConfigVariables.StringConfigVariable
  langs:
  - csharp
  - vb
  name: UCTools_ConfigVariables
  nameWithType: UCTools_ConfigVariables
  fullName: UCTools_ConfigVariables
  type: Namespace
  assemblies:
  - cs.temp.dll
references:
- uid: UCTools_ConfigVariables.ConfigCategory
  commentId: T:UCTools_ConfigVariables.ConfigCategory
  parent: UCTools_ConfigVariables
  name: ConfigCategory
  nameWithType: ConfigCategory
  fullName: UCTools_ConfigVariables.ConfigCategory
- uid: UCTools_ConfigVariables.ConfigFlags
  commentId: T:UCTools_ConfigVariables.ConfigFlags
  parent: UCTools_ConfigVariables
  name: ConfigFlags
  nameWithType: ConfigFlags
  fullName: UCTools_ConfigVariables.ConfigFlags
- uid: UCTools_ConfigVariables.QualityOption
  commentId: T:UCTools_ConfigVariables.QualityOption
  parent: UCTools_ConfigVariables
  name: QualityOption
  nameWithType: QualityOption
  fullName: UCTools_ConfigVariables.QualityOption
- uid: UCTools_ConfigVariables.QualityOptionExtensions
  commentId: T:UCTools_ConfigVariables.QualityOptionExtensions
  name: QualityOptionExtensions
  nameWithType: QualityOptionExtensions
  fullName: UCTools_ConfigVariables.QualityOptionExtensions
- uid: UCTools_ConfigVariables.ResolutionOption
  commentId: T:UCTools_ConfigVariables.ResolutionOption
  parent: UCTools_ConfigVariables
  name: ResolutionOption
  nameWithType: ResolutionOption
  fullName: UCTools_ConfigVariables.ResolutionOption
- uid: UCTools_ConfigVariables.ResolutionOptionExtensions
  commentId: T:UCTools_ConfigVariables.ResolutionOptionExtensions
  name: ResolutionOptionExtensions
  nameWithType: ResolutionOptionExtensions
  fullName: UCTools_ConfigVariables.ResolutionOptionExtensions
- uid: UCTools_ConfigVariables.BoolConfigVariable
  commentId: T:UCTools_ConfigVariables.BoolConfigVariable
  parent: UCTools_ConfigVariables
  name: BoolConfigVariable
  nameWithType: BoolConfigVariable
  fullName: UCTools_ConfigVariables.BoolConfigVariable
- uid: UCTools_ConfigVariables.ConfigVariableBase
  commentId: T:UCTools_ConfigVariables.ConfigVariableBase
  parent: UCTools_ConfigVariables
  name: ConfigVariableBase
  nameWithType: ConfigVariableBase
  fullName: UCTools_ConfigVariables.ConfigVariableBase
- uid: UCTools_ConfigVariables.EnumConfigVariable`1
  commentId: T:UCTools_ConfigVariables.EnumConfigVariable`1
  name: EnumConfigVariable<T>
  nameWithType: EnumConfigVariable<T>
  fullName: UCTools_ConfigVariables.EnumConfigVariable<T>
  nameWithType.vb: EnumConfigVariable(Of T)
  fullName.vb: UCTools_ConfigVariables.EnumConfigVariable(Of T)
  name.vb: EnumConfigVariable(Of T)
  spec.csharp:
  - uid: UCTools_ConfigVariables.EnumConfigVariable`1
    name: EnumConfigVariable
    nameWithType: EnumConfigVariable
    fullName: UCTools_ConfigVariables.EnumConfigVariable
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: UCTools_ConfigVariables.EnumConfigVariable`1
    name: EnumConfigVariable
    nameWithType: EnumConfigVariable
    fullName: UCTools_ConfigVariables.EnumConfigVariable
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: UCTools_ConfigVariables.FloatConfigVariable
  commentId: T:UCTools_ConfigVariables.FloatConfigVariable
  parent: UCTools_ConfigVariables
  name: FloatConfigVariable
  nameWithType: FloatConfigVariable
  fullName: UCTools_ConfigVariables.FloatConfigVariable
- uid: UCTools_ConfigVariables.IntConfigVariable
  commentId: T:UCTools_ConfigVariables.IntConfigVariable
  parent: UCTools_ConfigVariables
  name: IntConfigVariable
  nameWithType: IntConfigVariable
  fullName: UCTools_ConfigVariables.IntConfigVariable
- uid: UCTools_ConfigVariables.QualityConfigVariable
  commentId: T:UCTools_ConfigVariables.QualityConfigVariable
  parent: UCTools_ConfigVariables
  name: QualityConfigVariable
  nameWithType: QualityConfigVariable
  fullName: UCTools_ConfigVariables.QualityConfigVariable
- uid: UCTools_ConfigVariables.ResolutionConfigVariable
  commentId: T:UCTools_ConfigVariables.ResolutionConfigVariable
  parent: UCTools_ConfigVariables
  name: ResolutionConfigVariable
  nameWithType: ResolutionConfigVariable
  fullName: UCTools_ConfigVariables.ResolutionConfigVariable
- uid: UCTools_ConfigVariables.StringConfigVariable
  commentId: T:UCTools_ConfigVariables.StringConfigVariable
  name: StringConfigVariable
  nameWithType: StringConfigVariable
  fullName: UCTools_ConfigVariables.StringConfigVariable
- uid: UCTools_ConfigVariables
  commentId: N:UCTools_ConfigVariables
  name: UCTools_ConfigVariables
  nameWithType: UCTools_ConfigVariables
  fullName: UCTools_ConfigVariables
